# A quick message broker environment setup with rabbitmq message broker and a Rabbit management web client

# Docker compose file version
version: "3.9"

# All the Rabbit setup related services
services:
  # The Rabbitmq messaging service running on container port 5672 and published port value comes from .env file
  rabbit-messaging-server:
    image: "rabbitmq:3.8.16-management-alpine"
    restart: "always"
    ports:
      - "${RABBIT_PUBLISHED_PORT}:5672"
      - "${RABBIT_MANAGEMENT_PUBLISHED_PORT}:15672"
    networks:
      - dev-local
    env_file:
      - ./rabbit_messaging.env